<a href="https://colab.research.google.com/github/zzzer0-wav/Melbourne_Housing/blob/main/notebooks/melbourne_housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Melbourne housing

### Step 1 - loading dataset

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
FILE_IN = 'https://raw.githubusercontent.com/zzzer0-wav/Melbourne_Housing/refs/heads/main/data/dirty_melb_data.csv'
FILE_OUT = 'clean_melb_data'
df_origin = pd.read_csv(FILE_IN)
df = df_origin.copy()

In [ ]:
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns='Unnamed: 0')

### Step 2 - first look

In [ ]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [ ]:
df.shape

(13580, 21)

In [ ]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [ ]:
round(df.describe(), 2)

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.00,13580.00,13580.00,13580.00,13580.00,13580.00,13518.00,13580.00,7130.00,8205.00,13580.00,13580.00,13580.00
mean,2.94,1075684.08,10.14,3105.30,2.91,1.53,1.61,558.42,151.97,1964.68,-37.81,145.00,7454.42
std,0.96,639310.72,5.87,90.68,0.97,0.69,0.96,3990.67,541.01,37.27,0.08,0.10,4378.58
min,1.00,85000.00,0.00,3000.00,0.00,0.00,0.00,0.00,0.00,1196.00,-38.18,144.43,249.00
25%,2.00,650000.00,6.10,3044.00,2.00,1.00,1.00,177.00,93.00,1940.00,-37.86,144.93,4380.00
50%,3.00,903000.00,9.20,3084.00,3.00,1.00,2.00,440.00,126.00,1970.00,-37.80,145.00,6555.00
75%,3.00,1330000.00,13.00,3148.00,3.00,2.00,2.00,651.00,174.00,1999.00,-37.76,145.06,10331.00
max,10.00,9000000.00,48.10,3977.00,20.00,8.00,10.00,433014.00,44515.00,2018.00,-37.41,145.53,21650.00

In [ ]:
# MISSING VALUES

missing = df.isna().sum()
missing_pct = round(df.isna().mean() * 100, 2)
missing_table = pd.DataFrame({
    'type': df.dtypes.astype(str),
    'missing':missing,
    'missing_pct':missing_pct
})

missing_table

                  type  missing  missing_pct
Suburb          object        0         0.00
Address         object        0         0.00
Rooms            int64        0         0.00
Type            object        0         0.00
Price          float64        0         0.00
Method          object        0         0.00
SellerG         object        0         0.00
Date            object        0         0.00
Distance       float64        0         0.00
Postcode       float64        0         0.00
Bedroom2       float64        0         0.00
Bathroom       float64        0         0.00
Car            float64       62         0.46
Landsize       float64        0         0.00
BuildingArea   float64     6450        47.50
YearBuilt      float64     5375        39.58
CouncilArea     object     1369        10.08
Lattitude      float64        0         0.00
Longtitude     float64        0         0.00
Regionname      object        0         0.00
Propertycount  float64        0         0.00

### Step 3 - cleaning

In [ ]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [ ]:
# RENAME COLUMNS

df = df.rename(columns={
    'Suburb':'suburb',
    'Address':'address',
    'Rooms':'rooms',
    'Type':'type',
    'Price':'price',
    'Method':'method',
    'SellerG':'seller_g',
    'Date':'date',
    'Distance':'distance',
    'Postcode':'postcode',
    'Bedroom2':'bedroom2',
    'Bathroom':'bathroom',
    'Car':'car',
    'Landsize':'landsize',
    'BuildingArea':'building_area',
    'YearBuilt':'year_built',
    'CouncilArea':'council_area',
    'Lattitude':'lattitude',
    'Longtitude':'longtitude',
    'Regionname':'region_name',
    'Propertycount':'property_count'
})
print(list(df.columns))

['suburb', 'address', 'rooms', 'type', 'price', 'method', 'seller_g', 'date', 'distance', 'postcode', 'bedroom2', 'bathroom', 'car', 'landsize', 'building_area', 'year_built', 'council_area', 'lattitude', 'longtitude', 'region_name', 'property_count']

In [ ]:
# COLUMN TYPES
df.date.unique()[:]

array(['3/12/2016', '4/02/2016', '4/03/2017', '4/06/2016', '7/05/2016',
       '8/10/2016', '12/11/2016', '13/08/2016', '14/05/2016',
       '15/10/2016', '16/07/2016', '17/09/2016', '18/03/2017',
       '18/06/2016', '19/11/2016', '22/08/2016', '24/09/2016',
       '25/02/2017', '26/07/2016', '27/11/2016', '28/05/2016',
       '30/07/2016', '3/09/2016', '6/08/2016', '7/11/2016', '10/09/2016',
       '10/12/2016', '11/02/2017', '16/04/2016', '22/05/2016',
       '23/04/2016', '12/06/2016', '27/06/2016', '28/08/2016',
       '11/03/2017', '28/01/2016', '6/05/2017', '8/04/2017', '29/04/2017',
       '13/05/2017', '20/05/2017', '22/04/2017', '1/07/2017', '3/06/2017',
       '17/06/2017', '24/06/2017', '27/05/2017', '8/07/2017',
       '12/08/2017', '15/07/2017', '22/07/2017', '29/07/2017',
       '3/09/2017', '9/09/2017', '16/09/2017', '19/08/2017', '23/09/2017',
       '26/08/2017'], dtype=object)

In [ ]:
df['date'] = pd.to_datetime(df['date'], format='%d/%m/%Y')

In [ ]:
df['postcode'] = df['postcode'].astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   suburb          13580 non-null  object
 1   address         13580 non-null  object
 2   rooms           13580 non-null  int64
 3   type            13580 non-null  object
 4   price           13580 non-null  float64
 5   method          13580 non-null  object
 6   seller_g        13580 non-null  object
 7   date            13580 non-null  datetime64[ns]
 8   distance        13580 non-null  float64
 9   postcode        13580 non-null  int64
 10  bedroom2        13580 non-null  float64
 11  bathroom        13580 non-null  float64
 12  car             13518 non-null  float64
 13  landsize        13580 non-null  float64
 14  building_area   7130 non-null   float64
 15  year_built      8205 non-null   float64
 16  council_area    12211 non-null  object
 17  lattitude       13580 non-null  float64
 18  longtitude      13580 non-null  float64
 19  region_name     13580 non-null  object
 20  property_count  13580 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 2.2+ MB

In [ ]:
# zero values

zero_cols = ['building_area']

for col in zero_cols:
    df.loc[df[col]==0, col] = np.nan

In [ ]:
print(df[zero_cols].isna().sum())

building_area    6467
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   suburb          13580 non-null  object
 1   address         13580 non-null  object
 2   rooms           13580 non-null  int64
 3   type            13580 non-null  object
 4   price           13580 non-null  float64
 5   method          13580 non-null  object
 6   seller_g        13580 non-null  object
 7   date            13580 non-null  datetime64[ns]
 8   distance        13580 non-null  float64
 9   postcode        13580 non-null  int64
 10  bedroom2        13580 non-null  float64
 11  bathroom        13580 non-null  float64
 12  car             13518 non-null  float64
 13  landsize        13580 non-null  float64
 14  building_area   7113 non-null   float64
 15  year_built      8205 non-null   float64
 16  council_area    12211 non-null  object
 17  lattitude       13580 non-null  float64
 18  longtitude      13580 non-null  float64
 19  region_name     13580 non-null  object
 20  property_count  13580 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 2.2+ MB

In [ ]:
# removing wrong year
mask = (df['year_built'] < 1800) | (df['year_built'] > 2018)

df.loc[mask, 'year_built'] = np.nan

In [ ]:
print(df.describe().T)

                  count                           mean                  min  \
rooms           13580.0                       2.937997                  1.0
price           13580.0                 1075684.079455              85000.0
date              13580  2017-01-28 20:25:03.622974976  2016-01-28 00:00:00
distance        13580.0                      10.137776                  0.0
postcode        13580.0                    3105.301915               3000.0
bedroom2        13580.0                       2.914728                  0.0
bathroom        13580.0                       1.534242                  0.0
car             13518.0                       1.610075                  0.0
landsize        13580.0                     558.416127                  0.0
building_area    7113.0                     152.330851                  1.0
year_built       8204.0                    1964.777913               1830.0
lattitude       13580.0                     -37.809203            -38.18255
longtitude      13580.0                     144.995216            144.43181
property_count  13580.0                    7454.417378                249.0

                                25%                  50%                  75%  \
rooms                           2.0                  3.0                  3.0
price                      650000.0             903000.0            1330000.0
date            2016-09-10 00:00:00  2017-03-04 00:00:00  2017-06-24 00:00:00
distance                        6.1                  9.2                 13.0
postcode                     3044.0               3084.0               3148.0
bedroom2                        2.0                  3.0                  3.0
bathroom                        1.0                  1.0                  2.0
car                             1.0                  2.0                  2.0
landsize                      177.0                440.0                651.0
building_area                  93.0                126.0                174.0
year_built                   1940.0               1970.0               1999.0
lattitude                -37.856822           -37.802355             -37.7564
longtitude                 144.9296             145.0001           145.058305
property_count               4380.0               6555.0              10331.0

                                max            std
rooms                          10.0       0.955748
price                     9000000.0  639310.724296
date            2017-09-23 00:00:00            NaN
distance                       48.1       5.868725
postcode                     3977.0      90.676964
bedroom2                       20.0       0.965921
bathroom                        8.0       0.691712
car                            10.0       0.962634
landsize                   433014.0    3990.669241
building_area               44515.0     541.609671
year_built                   2018.0      36.296864
lattitude                 -37.40853        0.07926
longtitude                145.52635       0.103916
property_count              21650.0    4378.581772

In [ ]:
# removing wrong build area values

print(df['building_area'].sort_values().head(70))

8297      1.0
11902     1.0
4386      1.0
11931     1.0
8318      1.0
         ...
9945     16.0
4154     16.0
3491     18.0
6431     18.0
2336     18.0
Name: building_area, Length: 70, dtype: float64

In [ ]:
df.loc[df['building_area']<15, 'building_area'] = np.nan

After deleting 0 values in build area I found more weird min values from 1 to 15. Even smallest apartment cant be smaller then 15 m². So swaping values 0-14 to nan is good decision for analysis.

In [ ]:
# check duplicated

print(df.duplicated().sum())

# remove - df.drop_duplicated()

0

In [ ]:
# replacing missing values (with pct < 30%)

df['car'] = df['car'].fillna(df['car'].median())

In [ ]:
df['council_area'] = df['council_area'].fillna(df['council_area'].mode()[0])

In [ ]:
missing = df.isna().sum()
missing_pct = round(df.isna().mean() * 100, 2)
missing_table = pd.DataFrame({
    'type': df.dtypes.astype(str),
    'missing':missing,
    'missing_pct':missing_pct
})

missing_table

                          type  missing  missing_pct
suburb                  object        0         0.00
address                 object        0         0.00
rooms                    int64        0         0.00
type                    object        0         0.00
price                  float64        0         0.00
method                  object        0         0.00
seller_g                object        0         0.00
date            datetime64[ns]        0         0.00
distance               float64        0         0.00
postcode                 int64        0         0.00
bedroom2               float64        0         0.00
bathroom               float64        0         0.00
car                    float64        0         0.00
landsize               float64        0         0.00
building_area          float64     6530        48.09
year_built             float64     5376        39.59
council_area            object        0         0.00
lattitude              float64        0         0.00
longtitude             float64        0         0.00
region_name             object        0         0.00
property_count         float64        0         0.00

### Step 4 - EDA